apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
      - name: init-chown-data
        image: busybox
        command: ['sh', '-c', 'chown -R 1001:1001 /var/lib/ghost/content']
        volumeMounts:
        - name: ghost-content
          mountPath: /var/lib/ghost/content
      containers:
      - name: ghost
        image: ghost:4.32.0
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: "http://ghost.local/"
        - name: database__client
          value: "sqlite3"
        - name: database__connection__filename
          value: "/var/lib/ghost/content/data/ghost.db"
        volumeMounts:
        - name: ghost-content
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-content
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ghost
spec:
  selector:
    app: ghost
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2368
  type: LoadBalancer
