apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ghost
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ghost
  endpoints:
  - port: metrics
    interval: 30s
